create procedure screen
s3r6anita/mypet-vkEdu-project pull request #12
Opened 2024-03-12 11:18 UTC by MamykinVsevolod

2024-03-13 08:01 UTC, s3r6anita commented
сделай optimize imports

2024-03-16 09:58 UTC, s3r6anita approved these changes

2024-03-16 20:28 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/ProcedureScreen.kt
> +                    text = "some procedure name",
Resourse

2024-03-16 20:28 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/ProcedureScreen.kt
> +                    Icon(Icons.Rounded.Done, contentDescription = "Процедура выполнена")
Аналогично проверь в остальных местах

2024-03-16 20:29 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/ProcedureScreen.kt
> +                    .weight(1f)
Вес точно здесь нужен?

2024-03-16 20:29 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/ProcedureScreen.kt
> +                modifier = Modifier
modifier = Modifier??? 
Зачем?)

2024-03-16 20:30 UTC, zalmek requested changes
Поправить по комментам

2024-03-18 16:39 UTC, MamykinVsevolod commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/ProcedureScreen.kt
> +                    .weight(1f)
да, чтобы поле дял заметок было до низа экрана, а не полосочкой

2024-03-18 17:19 UTC, zalmek requested changes
Поправь ресурсы:)

2024-03-18 17:19 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/ProcedureScreen.kt
> +                text = "00:00",
Тут

2024-03-18 17:19 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/ProcedureScreen.kt
> +                text = "01.01.2024",
Тут

2024-03-18 17:19 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/ProcedureScreen.kt
> +                    text = "за 5 минут до процедуры",
Тут

2024-03-18 17:40 UTC, zalmek approved these changes

2024-03-18 20:19 UTC, merged