Design of list profile screen
s3r6anita/mypet-vkEdu-project pull request #14
Opened 2024-03-17 16:08 UTC by AlexandraShumailova

Change design of list profile screen

2024-03-17 16:45 UTC, ponomo2 approved these changes

2024-03-17 17:16 UTC, s3r6anita requested changes

2024-03-17 17:16 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/profile/ListProfileScreen.kt
> +                )
посмотри в классе Icons, нет ли чего-то подходящего и description в ресурсы вынеси в любом случае

2024-03-17 17:16 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/profile/ListProfileScreen.kt
> +            containerColor = White,
может через MaterialTheme.colorScheme сделать его цвет динамичным в зависимости от темы устройства или самим сделать смену цвета в зависимости от темы устройства

2024-03-17 17:16 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/profile/ListProfileScreen.kt
> +                tint = LightGrayTint)
через Icons?

2024-03-18 17:15 UTC, zalmek approved these changes
Всё отлично

2024-03-18 17:16 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/profile/ListProfileScreen.kt
> +                )
можно писать null

2024-03-18 17:17 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/profile/ListProfileScreen.kt
> +            containerColor = White,
Как хочешь, я честно скажу что не делал смену цвета в зависимости от устройства у меня везде была 1 тема

2024-03-18 17:48 UTC, s3r6anita commented
забыл удалить иконки, попробовал сделать аменд коммит и почему-то не получилось... отсюда второй коммит с таким же именем и мердж

2024-03-18 17:54 UTC, s3r6anita approved these changes

2024-03-18 20:32 UTC, merged