create CreateProcedureScreen
s3r6anita/mypet-vkEdu-project pull request #16
Opened 2024-03-19 02:16 UTC by MamykinVsevolod

2024-03-21 19:47 UTC, zalmek requested changes

2024-03-21 19:47 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/CreateProcedureScreen.kt
> +            val frequencyOptions =
Переделать в Enum Class

2024-03-21 19:47 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/CreateProcedureScreen.kt
> +                        trailingIcon = {
Resourse

2024-03-21 19:47 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/CreateProcedureScreen.kt
> +            val nameOptions = when (selectedType) {
Переделать в Enum Class

2024-03-21 19:47 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/CreateProcedureScreen.kt
> +            val typeOptions = listOf("Гигиеническая", "Медицинская", "Пользовательская")
Переделать в Enum Class

2024-03-21 19:47 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/CreateProcedureScreen.kt
> +                    label = { Text(text = "Период")},
Resourse

2024-03-21 19:47 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/CreateProcedureScreen.kt
> +                        Icon(Icons.Default.Clear, contentDescription = "Очистить")
contentDescription = null

2024-03-21 19:47 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/procedure/CreateProcedureScreen.kt
> +                        Icon(Icons.Default.Clear, contentDescription = "Очистить")
Либо в Resourse

2024-03-25 16:28 UTC, s3r6anita commented
оставшиеся нюансы будут исправлены в дальнейшей работе над экраном

2024-03-25 16:29 UTC, merged

2024-03-25 16:30 UTC, s3r6anita reviewed
вроде все ошибки по ревью поправил