Feature login registration screens
s3r6anita/mypet-vkEdu-project pull request #32
Opened 2024-04-22 17:09 UTC by AlexandraShumailova

2024-04-22 23:21 UTC, s3r6anita requested changes

2024-04-22 23:21 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/login/LoginScreen.kt
> +fun HelloScreen(){
Переименовать по названию файла

2024-04-22 23:21 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/login/LoginScreen.kt
> +                actions = {}
можно убрать

2024-04-22 23:21 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/login/LoginScreen.kt
> +            Button(
ентер добавить

2024-04-22 23:21 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/login/RegistrationScreen.kt
> +                actions = {}
то, что инициализировано по умолчанию - убрать

2024-04-23 13:35 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/login/RegistrationScreen.kt
> +    Scaffold() { innerPadding ->
Придирка - можно не исправлять: если вызываешь функцию без параметров скобки лучше не писать

2024-04-23 13:36 UTC, zalmek approved these changes
Молодец! Всегда хорошо делаешь ПРы.

2024-04-23 16:10 UTC, s3r6anita approved these changes

2024-04-23 16:10 UTC, merged