add network actions
s3r6anita/mypet-vkEdu-project pull request #38
Opened 2024-05-13 21:32 UTC by s3r6anita

add login and getProfiles with network

2024-05-14 16:55 UTC, zalmek requested changes

2024-05-14 16:55 UTC, zalmek commented on app/src/main/java/com/f4/mypet/data/network/authentication/JwtTokenManager.kt
> +    //    suspend fun saveRefreshJwt(token: String)
Почему закоменчено?

2024-05-14 16:55 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/components/MyPetTopBar.kt
> +    modifier: Modifier = Modifier, //zalmek
Мои комменты нужно было удалить или поправить)

2024-05-14 16:55 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/login/LoginScreen.kt
> +        mutableStateOf("admin@admin.com")
Хардкодный хардкод

2024-05-15 07:42 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/data/network/authentication/JwtTokenManager.kt
> +    //    suspend fun saveRefreshJwt(token: String)
на сервере не реализовано, нужно в принципе убрать, изначально думал реализовать и на сервере

2024-05-15 07:43 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/components/MyPetTopBar.kt
> +    modifier: Modifier = Modifier, //zalmek
не заметил этот

2024-05-15 07:43 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/login/LoginScreen.kt
> +        mutableStateOf("admin@admin.com")
ага, для тестов делал так, чтобы не вводить каждый раз, забыл убрать

2024-05-17 21:46 UTC, zalmek commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
http запросы есть?

2024-05-17 21:47 UTC, zalmek commented on app/src/main/java/com/f4/mypet/data/db/DBRepository.kt
>      suspend fun getPetForCU(petId: Int): Pet
По хорошему на уровне репозитория всё должно быть обёрнуто во флоу

2024-05-17 21:51 UTC, zalmek approved these changes
Почитай комменты

2024-05-18 08:41 UTC, s3r6anita commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
изначально были, но теперь надо убрать

2024-05-18 08:42 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/data/db/DBRepository.kt
>      suspend fun getPetForCU(petId: Int): Pet
там возникает проблема при использровании collect, про которую  я тебе писал в лс
 поэтому пока без flow, но с uiState

2024-05-18 09:42 UTC, merged