vk wall and share pet info
s3r6anita/mypet-vkEdu-project pull request #39
Opened 2024-05-27 20:04 UTC by ponomo2

add posts from vkpets with interface and share pet info

2024-05-27 21:40 UTC, zalmek requested changes

2024-05-27 21:40 UTC, zalmek commented on app/build.gradle.kts
> +            "VKIDRedirectScheme" to "vk51926140", // обычно vk{ID приложения}
В localParams вынести

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/navigation/MainNavGraph.kt
> +    context: Context
Контекс никуда не передаём в UI слое

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/navigation/MainNavGraph.kt
> +                context = context
внутри есть контекст по умолчанию

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/navigation/MainNavGraph.kt
> +                context = context,
внутри есть контекст по умолчанию

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/navigation/SetupNavGraph.kt
> +    context: Context
внутри есть контекст по умолчанию

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/auth/login/LoginScreen.kt
> +    context: Context,
внутри есть контекст по умолчанию

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/auth/login/LoginScreen.kt
> +    val vkid = VKID(LocalContext.current)
Тем более ты его здесь вызывыешь)))

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/profile/show/ProfileScreen.kt
> +    context: Context,
внутри есть контекст по умолчанию

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/profile/show/ProfileScreen.kt
> +                            viewModel.sharePetInfo(message, context)
LocalContext.current

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/wall/PetsWallViewModel.kt
> +            token = "vk1.a.WMwyI6S-BkkNFwJ5bRc_ymj6NKKI" +
Токен храним в секьюрных префах хотя бы, не хардкодим

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/wall/elements/PhotoCarousel.kt
> +    photos: List<WallWallpostAttachmentDto>,
ImmutableList

2024-05-27 21:40 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/wall/elements/WallItem.kt
> +    LazyColumn(modifier = modifier,
Зачем Lazy, если всё равно никак это не используешь.
Lazy когда все элементы однотипные, в остальных случаях - Column(если нужно через Modifier добавляем скролл)

2024-05-27 21:42 UTC, zalmek commented on app/src/main/java/com/f4/mypet/MyPetApp.kt
> +fun MyPetApp(context: Context) {
Тоже лишний контекст

2024-05-27 21:42 UTC, zalmek commented on app/src/main/java/com/f4/mypet/MyPetApp.kt
> +            context = context
И тут

2024-05-27 23:04 UTC, s3r6anita commented on app/src/main/java/com/f4/mypet/ui/screens/wall/PetsWallViewModel.kt
> +            token = "vk1.a.WMwyI6S-BkkNFwJ5bRc_ymj6NKKI" +
сохранение в префы и взятие оттуда у меня в ветке, на этапе мерджа добавим

2024-05-28 06:37 UTC, ponomo2 commented on app/src/main/java/com/f4/mypet/ui/screens/wall/elements/WallItem.kt
> +    LazyColumn(modifier = modifier,
ну чтобы оно заранее всё не прогружалось. фотки, например

2024-05-28 07:38 UTC, s3r6anita approved these changes

2024-05-28 12:00 UTC, zalmek commented on app/src/main/java/com/f4/mypet/ui/screens/wall/elements/WallItem.kt
> +    LazyColumn(modifier = modifier,
Оно не будет в любрм случае, в компоуз грузится только то что видно на экране

2024-05-28 12:02 UTC, zalmek approved these changes

2024-05-28 12:10 UTC, merged